import edu.ucdavis.jr.JR;

public class main
{
    static op void p(int) throws java.io.EOFException;
    static void p(int i) throws java.io.EOFException
    {
	throw new java.io.EOFException("from method p");
    }
    static op void p2(int) throws java.io.EOFException;
    static void p2(int i) throws java.io.EOFException
    {
	    forward p(3) handler new Handler2();
	throw new java.io.EOFException("from method p2");
    }

    public static void main(String [] args)
    {
	    send p2(3) handler new Handler();
	    try
	    {
		call p2(4);
	    }
	    catch (java.io.EOFException e)
	    {
		System.out.println("Caught through call to p2 with try/catch: " + e.toString());
	    }
	    // mix things up for better testing:
	    for (int i = 0; i < 100; i++) Thread.yield();
	    // oops, might exit before handler done.
	    // JR.exit(0);
    }
}

class Handler implements edu.ucdavis.jr.Handler
{
    public handler void method(java.io.EOFException e)
    {
	System.out.println("Caught java.io.EOFException " +
				"through Handler object: " + e.toString());
    }
}

class Handler2 implements edu.ucdavis.jr.Handler
{
    public handler void method(java.io.EOFException e)
    {
	System.out.println("Caught java.io.EOFException " +
				"through Handler2 object: " + e.toString());
    }
}

