calling f.foo()
back from calling f.foo()
